name = "sdata"
description = "A data command interpreter for tabular data processing."
version = "0.8.0"

authors = ["John L. Ries"]
maintainers = ["John L. Ries <john@theyarnbard.com>"]
licenses = "GPL-3.0-only"
website = ""
tags = []

executables = ["sdata"]

[[depends-on]]
zipada = "^61.0.0"

[[depends-on]]
xmlada = "^26.0.0"

[[depends-on]]
mathpaqs = "^20260205.0.0"

[[depends-on]]
ada_sqlite3 = "^0.1.1"

[[depends-on]]
sdata_core = "^0.1.0"

[[pins]]
sdata_core = { path = "../sdata-core" }
