name = "sdata"
description = "A data command interpreter for tabular data processing."
version = "0.3.2"

authors = ["John L. Ries"]
maintainers = ["John L. Ries <john@theyarnbard.com>"]
licenses = "MIT"
website = ""
tags = []

executables = ["sdata"]

[[depends-on]]
zipada = "^62.0.0"

[[depends-on]]
xmlada = "^21.0.0"

[[depends-on]]
mathpaqs = "^20230121.0.0"
