--  Copyright (C) 2026 John L. Ries <john@theyarnbard.com>
--  License: GNU General Public License v3 or later
--  See LICENSE or <https://www.gnu.org/licenses/gpl-3.0.html>

--  Package SData.AST defines the Abstract Syntax Tree (AST) structure for the SData language.
--  It consists of nested variant records representing expressions and statements,
--  which are generated by the parser and processed by the evaluator and interpreter.

with Ada.Containers.Vectors;
with SData_Core.Config;
with SData_Core.Evaluator; use SData_Core.Evaluator;

package SData.AST is

   --  Expression types (Expression_Kind, Binary_Op, Unary_Op, Expression,
   --  Expression_Access, Expression_List, Expression_List_Node, and
   --  Free_Expression) are defined in SData_Core.Evaluator and made visible
   --  here via the use clause above.

   --  Represents a single variable or a range (e.g., VAR1-VAR10 or VAR1:VAR10).
   type Variable_Range is record
      Start_Name     : String (1 .. Max_Name_Len);
      Start_Len      : Natural;
      End_Name       : String (1 .. Max_Name_Len);
      End_Len        : Natural;
      Is_Range       : Boolean := False;
      Is_Colon_Range : Boolean := False;  -- True when separator was ':'
   end record;

   --  Linked list for variable lists in KEEP/DROP statements.
   type Variable_List_Node;
   type Variable_List is access Variable_List_Node;
   type Variable_List_Node is record
      Var  : Variable_Range;
      Next : Variable_List;
   end record;

   --  List for RENAME command pairs.
   type Rename_Pair_Node;
   type Rename_List is access Rename_Pair_Node;
   type Rename_Pair_Node is record
      Old_Name : String (1 .. Max_Name_Len);
      Old_Len  : Natural;
      New_Name : String (1 .. Max_Name_Len);
      New_Len  : Natural;
      Next     : Rename_List;
   end record;

   --  Shared by Dataset_Spec and Save_Spec: per-element option payload.
   --  Empty / null lists mean "not specified".
   type Spec_Options is record
      Format_Specified : Boolean := False;
      Fmt_Override     : SData_Core.Config.Format_Type :=
                            SData_Core.Config.CSV;
      Header_Specified : Boolean := False;
      Header_Val       : Boolean := True;
      Charset_Val      : String (1 .. Max_Charset_Len) := (others => ' ');
      Charset_Len      : Natural := 0;
      DLM_Val          : String (1 .. Max_Delimiter_Len) := (others => ' ');
      DLM_Len          : Natural := 0;
      NSCAN_Val        : Natural := 0;   --  USE only
      Skip_Val         : Natural := 0;   --  USE only
      Maxrows_Val      : Natural := 0;   --  USE only
      Sheet_Name       : String (1 .. Max_Sheet_Name_Len) :=
                            (others => ' ');
      Sheet_Name_Len   : Natural := 0;
      Keep_Vars        : Variable_List;        --  null = not specified
      Drop_Vars        : Variable_List;
      Rename_Pairs     : Rename_List;
      IN_Name          : String (1 .. Max_Name_Len) := (others => ' ');
      IN_Name_Len      : Natural := 0;          --  USE only; 0 = not set
      IF_Expr          : Expression_Access;     --  SAVE only; null = not set
   end record;

   type Dataset_Spec is record
      File_Path     : String (1 .. Max_Path_Len) := (others => ' ');
      File_Len      : Natural := 0;
      Is_Mock       : Boolean := False;
      Alias         : String (1 .. Max_Name_Len) := (others => ' ');
      Alias_Len     : Natural := 0;             --  0 = no alias
      Opts          : Spec_Options;
   end record;
   type Dataset_Spec_Access is access all Dataset_Spec;

   package Dataset_Spec_Vectors is new Ada.Containers.Vectors
     (Index_Type => Positive, Element_Type => Dataset_Spec_Access);

   type Save_Spec is record
      File_Path     : String (1 .. Max_Path_Len) := (others => ' ');
      File_Len      : Natural := 0;
      Alias         : String (1 .. Max_Name_Len) := (others => ' ');
      Alias_Len     : Natural := 0;             --  0 = no alias
      Opts          : Spec_Options;
   end record;
   type Save_Spec_Access is access all Save_Spec;

   package Save_Spec_Vectors is new Ada.Containers.Vectors
     (Index_Type => Positive, Element_Type => Save_Spec_Access);

   --  One "<outvar> = <fn>(<invar>)" clause of an AGGREGATE statement.
   --  Mirrors SData_Core.Commands.Aggregate_Spec; the interpreter converts a
   --  vector of these into the core type at dispatch.  Invar_Kind classifies
   --  the input reference (resolved at parse time via Has_Array):
   --    Invar_Empty         N() with no argument -> group row count
   --    Invar_Scalar        a scalar column name
   --    Invar_Array_Element an array element, e.g. x(1) (Invar_Index set)
   --    Invar_Array_Name    a whole registered array, applied element-wise
   type Aggregate_Invar_Kind is
     (Invar_Empty, Invar_Scalar, Invar_Array_Element, Invar_Array_Name);

   type Aggregate_Spec is record
      Outvar         : String (1 .. Max_Name_Len) := (others => ' ');
      Outvar_Len     : Natural := 0;
      Fn_Name        : String (1 .. Max_Name_Len) := (others => ' ');
      Fn_Name_Len    : Natural := 0;
      Invar_Kind     : Aggregate_Invar_Kind := Invar_Empty;
      Invar_Name     : String (1 .. Max_Name_Len) := (others => ' ');
      Invar_Name_Len : Natural := 0;
      Invar_Index    : Natural := 0;
   end record;
   type Aggregate_Spec_Access is access all Aggregate_Spec;

   package Aggregate_Spec_Vectors is new Ada.Containers.Vectors
     (Index_Type => Positive, Element_Type => Aggregate_Spec_Access);

   type Merge_Mode is (MM_Single, MM_Positional, MM_Match,
                       MM_Interleave, MM_Join, MM_Append);

   type Statement;
   type Statement_Access is access Statement;

   --  Branches for the SELECT statement.
   type Case_Branch_Node;
   type Case_Branch is access Case_Branch_Node;
   type Case_Branch_Node is record
      Conditions : Expression_List; -- List of values to match against selector
      Branch_Body : Statement_Access;
      Next       : Case_Branch;
   end record;

   --  Types of statements (commands) available in SData.
   type Statement_Kind is (
      Stmt_LET,    -- Variable assignment
      Stmt_SET,    -- Temporary assignment
      Stmt_UNSET,  -- Session variable removal
      Stmt_PRINT,  -- Output to console
      Stmt_USE,    -- Load dataset
      Stmt_SAVE,   -- Save dataset
      Stmt_KEEP,   -- Keep specific columns
      Stmt_DROP,   -- Drop specific columns
      Stmt_RENAME, -- Rename variables
      Stmt_IF,     -- Conditional execution
      Stmt_FOR,    -- Loop
      Stmt_WHILE,  -- Loop
      Stmt_REPEAT, -- Loop (Data Step creation)
      Stmt_LOOP_REPEAT, -- REPEAT/UNTIL loop
      Stmt_END,    -- Terminate program
      Stmt_QUIT,   -- Terminate program
      Stmt_NAMES,  -- List column names
      Stmt_LIST,   -- Display record data
      Stmt_SUBMIT, -- Recursive script execution
      Stmt_SYSTEM, -- External command execution
      Stmt_RSEED,  -- Set random seed
      Stmt_HOLD,   -- Retain variable values across records
      Stmt_UNHOLD, -- Reset variables normally
      Stmt_ARRAY,  -- Define a group of variables
      Stmt_DIM,    -- Real array (generates numbered variables)
      Stmt_SORT,   -- Sort the dataset
      Stmt_BY,     -- Group processing
      Stmt_SELECT, -- Multi-way branch
      Stmt_SELECT_FILTER, -- Record filter (declarative)
      Stmt_DELETE, -- Drop current record
      Stmt_BREAK,  -- Pause execution for inspection (BREAK / BREAK WHEN <expr>)
      Stmt_WRITE,  -- Explicit record output (was Stmt_OUTPUT)
      Stmt_OUTPUT, -- Console output redirection
      Stmt_ECHO,   -- Console output control
      Stmt_DIGITS, -- Set precision
      Stmt_FPATH,  -- Set default directories
      Stmt_HELP,   -- Display help
      Stmt_RUN,            -- Execute and export
      Stmt_NEW,            -- Reset environment
      Stmt_PROGRAM_DELETE, -- Delete line(s) from program buffer (immediate)
      Stmt_DISPLAY,        -- Display Data Table rows (immediate)
      Stmt_OPTIONS,        -- Set runtime option (OPTIONS key value)
      Stmt_AGGREGATE,      -- Collapse table to one row per BY group (immediate)
      Stmt_TRANSPOSE,      -- Reshape table columns to rows (immediate)
      Stmt_PROGRAM_INSERT  -- Set program-buffer insertion cursor (immediate)
   );

   type Statement (Kind : Statement_Kind) is record
      Next     : Statement_Access; -- Pointer to the next statement in sequence.
      Var_Name : String (1 .. Max_Name_Len);
      Var_Len  : Natural;
      Is_Array     : Boolean         := False;
      Arr_Idx      : Expression_Access;           -- single-subscript assignment
      Arr_Idx_List : Expression_List  := null;    -- list or range subscripts
      Arr_Is_Slice : Boolean         := False;    -- True when Arr_Idx_List is a lo:hi range
      Expr         : Expression_Access;
      case Kind is
         when Stmt_PRINT =>
            Print_Args : Expression_List;
         when Stmt_USE | Stmt_SAVE | Stmt_SUBMIT | Stmt_SYSTEM | Stmt_HELP | Stmt_OUTPUT | Stmt_FPATH =>
            File_Path : String (1 .. Max_Path_Len);
            File_Len  : Natural;
            Is_Mock     : Boolean := False; -- For USE MOCK
            Use_Flag    : Boolean := False; -- For FPATH
            Save_Flag   : Boolean := False; -- For FPATH
            Submit_Flag : Boolean := False; -- For FPATH
            Output_Flag : Boolean := False; -- For FPATH

            -- Command-specific overrides (/FMT, /NSCAN, /DLM, /HEADER, /SHEET, /SKIP, /MAXROWS)
            Format_Specified : Boolean := False;
            Fmt_Override     : SData_Core.Config.Format_Type := SData_Core.Config.CSV;
            NSCAN_Val        : Natural := 0;
            Skip_Val         : Natural := 0;
            Maxrows_Val      : Natural := 0;
            Header_Specified : Boolean := False;
            Header_Val       : Boolean := True;
            DLM_Path         : String (1 .. Max_Delimiter_Len)  := (others => ' ');
            DLM_Len          : Natural := 0;
            Sheet_Name         : String (1 .. Max_Sheet_Name_Len) := (others => ' ');
            Sheet_Name_Len     : Natural := 0;
            Output_FMT_Val     : String (1 .. Max_Delimiter_Len)  := (others => ' ');
            Output_FMT_Len     : Natural := 0;
            Output_CHARSET_Val : String (1 .. Max_Charset_Len)    := (others => ' ');
            Output_CHARSET_Len : Natural := 0;
            --  --- Multi-dataset extensions (USE) and multi-target (SAVE) ---
            --  When Dataset_List is non-empty, the parser used the new
            --  multi-dataset USE grammar; Execute_USE should iterate it.
            --  When empty, fall back to the legacy single-file fields above.
            Dataset_List   : Dataset_Spec_Vectors.Vector;
            --  Whole-statement options for multi-dataset USE.
            By_Vars        : Variable_List;
            Mode           : Merge_Mode := MM_Single;
            --  When Save_List is non-empty, the parser used the new
            --  multi-target SAVE grammar; Execute_SAVE iterates it.
            --  When empty, fall back to the legacy single-file fields.
            Save_List      : Save_Spec_Vectors.Vector;
         when Stmt_REPEAT =>
            Count : Natural;
         when Stmt_KEEP | Stmt_DROP | Stmt_HOLD | Stmt_UNHOLD | Stmt_UNSET | Stmt_ARRAY | Stmt_DIM | Stmt_DISPLAY =>
            Vars         : Variable_List;
            Arr_Name     : String (1 .. Max_Name_Len);
            Arr_Name_Len : Natural := 0;
            Arr_Dim      : Positive; -- Number of elements (for simple arrays) - this will become derived for DIM
            Arr_Vars     : Variable_List;
            Arr_Start_Expr : Expression_Access;  -- For DIM array lower bound
            Arr_End_Expr   : Expression_Access;  -- For DIM array upper bound
            Is_Custom_Subscripts : Boolean := False; -- For DIM arrays (e.g., (0:11))
            Is_Temporary_Dim     : Boolean := False; -- For DIM arrays /TEMP flag
         when Stmt_RENAME =>
            Rename_Pairs : Rename_List;
         when Stmt_IF =>
            Condition    : Expression_Access;
            Then_Branch  : Statement_Access;
            Else_Branch  : Statement_Access;
         when Stmt_FOR =>
            For_Var      : String (1 .. Max_Name_Len);
            For_Var_Len  : Natural;
            For_Start    : Expression_Access;
            For_End      : Expression_Access;
            For_Step     : Expression_Access;
            For_Body     : Statement_Access;
         when Stmt_WHILE =>
            While_Cond   : Expression_Access;
            While_Body   : Statement_Access;
         when Stmt_LOOP_REPEAT =>
            Repeat_Body  : Statement_Access;
            Until_Cond   : Expression_Access;
         when Stmt_RSEED =>
            Seed_Expr    : Expression_Access;
         when Stmt_SELECT =>
            Selector       : Expression_Access;
            Branches       : Case_Branch;
            Otherwise_Part : Statement_Access;
         when Stmt_SORT | Stmt_BY =>
            Sort_Vars      : Variable_List;
         when Stmt_ECHO =>
            Echo_State : Boolean;
         when Stmt_DIGITS =>
            Digits_Count   : Natural;
         when Stmt_PROGRAM_DELETE =>
            Delete_From : Positive := 1;
            Delete_To   : Positive := 1;
         when Stmt_OPTIONS =>
            Options_Key     : String (1 .. Max_Name_Len);
            Options_Key_Len : Natural := 0;
            Options_Val     : String (1 .. Max_Options_Val_Len);
            Options_Val_Len : Natural := 0;
         when Stmt_WRITE =>
            --  Empty Write_Targets = legacy bare WRITE (write to all
            --  registered SAVE targets). Non-empty = route only to these.
            Write_Targets : Variable_List;
         when Stmt_AGGREGATE =>
            Agg_List : Aggregate_Spec_Vectors.Vector;
         when Stmt_TRANSPOSE =>
            Keep_Vars    : Variable_List;
            Drop_Vars    : Variable_List;
            Name_Col     : String (1 .. Max_Name_Len); Name_Col_Len  : Natural := 0;
            Id_Col       : String (1 .. Max_Name_Len); Id_Col_Len    : Natural := 0;
            Array_Col    : String (1 .. Max_Name_Len); Array_Col_Len : Natural := 0;
            Has_Id       : Boolean := False;
            Has_Array    : Boolean := False;
         when Stmt_PROGRAM_INSERT =>
            Insert_At_End : Boolean := True;   --  True = append at end ($/bare)
            Insert_Line   : Natural := 0;      --  cursor after line N (0 = start)
            Insert_Bad    : Boolean := False;  --  negative/invalid argument
         when others =>
            null;
      end case;
   end record;

   --  Recursively free an entire statement list (program) and all AST nodes
   --  reachable from it (expressions, sub-bodies, variable lists, etc.).
   --  Sets Prog to null on return.  Safe to call with Prog = null.
   procedure Free_Program (Prog : in out Statement_Access);

   --  Deep-copies an expression tree.
   function Copy_Expression (Expr : Expression_Access) return Expression_Access;

   --  Free_Expression is provided by SData_Core.Evaluator (visible via use clause).

end SData.AST;