--  Package SData.AST defines the Abstract Syntax Tree (AST) structure for the SData language.
--  It consists of nested variant records representing expressions and statements,
--  which are generated by the parser and processed by the evaluator and interpreter.

with SData.Config;
with Ada.Strings.Unbounded;

package SData.AST is

   --  Kinds of expressions supported in the language.
   type Expression_Kind is (
      Expr_Numeric_Literal, -- e.g., 123.45
      Expr_String_Literal,  -- e.g., "Hello"
      Expr_Variable,        -- e.g., SALARY
      Expr_Binary_Op,       -- e.g., A + B
      Expr_Unary_Op,        -- e.g., -A
      Expr_Function_Call,   -- e.g., SQRT(X)
      Expr_Array_Access     -- e.g., ARR{1}
   );

   --  Arithmetic and logical binary operators.
   type Binary_Op is (Op_Add, Op_Sub, Op_Mul, Op_Div, Op_Pow, Op_Eq, Op_Ne, Op_Lt, Op_Le, Op_Gt, Op_Ge, Op_And, Op_Or, Op_Xor);
   
   --  Unary operators.
   type Unary_Op is (Op_Neg, Op_Not);

   type Expression;
   type Expression_Access is access Expression;

   --  Linked list structure for function arguments.
   type Expression_List_Node;
   type Expression_List is access Expression_List_Node;
   type Expression_List_Node is record
      Expr : Expression_Access;
      Next : Expression_List;
   end record;

   --  Variant record for all expression types.
   type Expression (Kind : Expression_Kind) is record
      case Kind is
         when Expr_Numeric_Literal =>
            Value      : Float;
            Is_Integer : Boolean := False;
            Int_Value  : Integer := 0;
         when Expr_String_Literal =>
            Str_Value : Ada.Strings.Unbounded.Unbounded_String;
         when Expr_Variable =>
            Var_Name : String (1 .. 32);
            Var_Len  : Natural;
         when Expr_Binary_Op =>
            Left  : Expression_Access;
            Right : Expression_Access;
            Op    : Binary_Op;
         when Expr_Unary_Op =>
            Operand : Expression_Access;
            UOp     : Unary_Op;
         when Expr_Function_Call =>
            Func_Name : String (1 .. 32);
            Func_Len  : Natural;
            Arguments : Expression_List;
         when Expr_Array_Access =>
            Arr_Name : String (1 .. 32);
            Arr_Len  : Natural;
            Arr_Idx  : Expression_List; -- Supports multiple subscripts: X(1, 3, 5)
      end case;
   end record;

   --  Represents a single variable or a range (e.g., VAR1-VAR10).
   type Variable_Range is record
      Start_Name : String (1 .. 32);
      Start_Len  : Natural;
      End_Name   : String (1 .. 32);
      End_Len    : Natural;
      Is_Range   : Boolean := False;
   end record;

   --  Linked list for variable lists in KEEP/DROP statements.
   type Variable_List_Node;
   type Variable_List is access Variable_List_Node;
   type Variable_List_Node is record
      Var  : Variable_Range;
      Next : Variable_List;
   end record;

   --  List for RENAME command pairs.
   type Rename_Pair_Node;
   type Rename_List is access Rename_Pair_Node;
   type Rename_Pair_Node is record
      Old_Name : String (1 .. 32);
      Old_Len  : Natural;
      New_Name : String (1 .. 32);
      New_Len  : Natural;
      Next     : Rename_List;
   end record;

   type Statement;
   type Statement_Access is access Statement;

   --  Branches for the SELECT statement.
   type Case_Branch_Node;
   type Case_Branch is access Case_Branch_Node;
   type Case_Branch_Node is record
      Conditions : Expression_List; -- List of values to match against selector
      Branch_Body : Statement_Access;
      Next       : Case_Branch;
   end record;

   --  Types of statements (commands) available in SData.
   type Statement_Kind is (
      Stmt_LET,    -- Variable assignment
      Stmt_SET,    -- Temporary assignment
      Stmt_UNSET,  -- Session variable removal
      Stmt_PRINT,  -- Output to console
      Stmt_USE,    -- Load dataset
      Stmt_SAVE,   -- Save dataset
      Stmt_KEEP,   -- Keep specific columns
      Stmt_DROP,   -- Drop specific columns
      Stmt_RENAME, -- Rename variables
      Stmt_IF,     -- Conditional execution
      Stmt_FOR,    -- Loop
      Stmt_WHILE,  -- Loop
      Stmt_REPEAT, -- Loop (Data Step creation)
      Stmt_LOOP_REPEAT, -- REPEAT/UNTIL loop
      Stmt_END,    -- Terminate program
      Stmt_QUIT,   -- Terminate program
      Stmt_NAMES,  -- List column names
      Stmt_LIST,   -- Display record data
      Stmt_SUBMIT, -- Recursive script execution
      Stmt_SYSTEM, -- External command execution
      Stmt_RSEED,  -- Set random seed
      Stmt_HOLD,   -- Retain variable values across records
      Stmt_UNHOLD, -- Reset variables normally
      Stmt_ARRAY,  -- Define a group of variables
      Stmt_DIM,    -- Real array (generates numbered variables)
      Stmt_SORT,   -- Sort the dataset
      Stmt_BY,     -- Group processing
      Stmt_SELECT, -- Multi-way branch
      Stmt_SELECT_FILTER, -- Record filter (declarative)
      Stmt_DELETE, -- Drop current record
      Stmt_WRITE,  -- Explicit record output (was Stmt_OUTPUT)
      Stmt_OUTPUT, -- Console output redirection
      Stmt_ECHO,   -- Console output control
      Stmt_DIGITS, -- Set precision
      Stmt_FPATH,  -- Set default directories
      Stmt_HELP,   -- Display help
      Stmt_RUN,            -- Execute and export
      Stmt_NEW,            -- Reset environment
      Stmt_PROGRAM_DELETE, -- Delete line(s) from program buffer (immediate)
      Stmt_DISPLAY         -- Display Data Table rows (immediate)
   );

   type Statement (Kind : Statement_Kind) is record
      Next     : Statement_Access; -- Pointer to the next statement in sequence.
      Var_Name : String (1 .. 32);
      Var_Len  : Natural;
      Is_Array : Boolean := False;
      Arr_Idx  : Expression_Access;
      Expr     : Expression_Access;
      case Kind is
         when Stmt_PRINT =>
            Print_Args : Expression_List;
         when Stmt_USE | Stmt_SAVE | Stmt_SUBMIT | Stmt_SYSTEM | Stmt_HELP | Stmt_OUTPUT | Stmt_FPATH =>
            File_Path : String (1 .. 1024);
            File_Len  : Natural;
            Is_Mock     : Boolean := False; -- For USE MOCK
            Use_Flag    : Boolean := False; -- For FPATH
            Save_Flag   : Boolean := False; -- For FPATH
            Submit_Flag : Boolean := False; -- For FPATH
            Output_Flag : Boolean := False; -- For FPATH
            
            -- Command-specific overrides (/FMT, /NSCAN, /DLM, /HEADER, /SHEET)
            Format_Specified : Boolean := False;
            Fmt_Override     : SData.Config.Format_Type := SData.Config.CSV;
            NSCAN_Val        : Natural := 0;
            Header_Specified : Boolean := False;
            Header_Val       : Boolean := True;
            DLM_Path         : String (1 .. 32) := (others => ' ');
            DLM_Len          : Natural := 0;
            Sheet_Name       : String (1 .. 64) := (others => ' ');
            Sheet_Name_Len   : Natural := 0;
         when Stmt_REPEAT =>
            Count : Natural;
         when Stmt_KEEP | Stmt_DROP | Stmt_HOLD | Stmt_UNHOLD | Stmt_UNSET | Stmt_ARRAY | Stmt_DIM | Stmt_DISPLAY =>
            Vars         : Variable_List;
            Arr_Name     : String (1 .. 32);
            Arr_Name_Len : Natural;
            Arr_Dim      : Positive; -- Number of elements (for simple arrays) - this will become derived for DIM
            Arr_Vars     : Variable_List;
            Arr_Start_Expr : Expression_Access;  -- For DIM array lower bound
            Arr_End_Expr   : Expression_Access;  -- For DIM array upper bound
            Is_Custom_Subscripts : Boolean := False; -- For DIM arrays (e.g., (0:11))
            Is_Temporary_Dim     : Boolean := False; -- For DIM arrays /TEMP flag
         when Stmt_RENAME =>
            Rename_Pairs : Rename_List;
         when Stmt_IF =>
            Condition    : Expression_Access;
            Then_Branch  : Statement_Access;
            Else_Branch  : Statement_Access;
         when Stmt_FOR =>
            For_Var      : String (1 .. 32);
            For_Var_Len  : Natural;
            For_Start    : Expression_Access;
            For_End      : Expression_Access;
            For_Step     : Expression_Access;
            For_Body     : Statement_Access;
         when Stmt_WHILE =>
            While_Cond   : Expression_Access;
            While_Body   : Statement_Access;
         when Stmt_LOOP_REPEAT =>
            Repeat_Body  : Statement_Access;
            Until_Cond   : Expression_Access;
         when Stmt_RSEED =>
            Seed_Expr    : Expression_Access;
         when Stmt_SELECT =>
            Selector       : Expression_Access;
            Branches       : Case_Branch;
            Otherwise_Part : Statement_Access;
         when Stmt_SORT | Stmt_BY =>
            Sort_Vars      : Variable_List;
         when Stmt_ECHO =>
            Echo_State : Boolean;
         when Stmt_DIGITS =>
            Digits_Count   : Natural;
         when Stmt_PROGRAM_DELETE =>
            Delete_From : Positive := 1;
            Delete_To   : Positive := 1;
         when others =>
            null;
      end case;
   end record;

   --  Recursively free an entire statement list (program) and all AST nodes
   --  reachable from it (expressions, sub-bodies, variable lists, etc.).
   --  Sets Prog to null on return.  Safe to call with Prog = null.
   procedure Free_Program (Prog : in out Statement_Access);

   --  Deep-copies an expression tree.
   function Copy_Expression (Expr : Expression_Access) return Expression_Access;

   --  Frees a single expression tree.
   procedure Free_Expression (Expr : in out Expression_Access);

end SData.AST;
