--  Package SData.AST defines the Abstract Syntax Tree (AST) structure for the SData language.
--  It consists of nested variant records representing expressions and statements,
--  which are generated by the parser and processed by the evaluator and interpreter.

package SData.AST is

   --  Kinds of expressions supported in the language.
   type Expression_Kind is (
      Expr_Numeric_Literal, -- e.g., 123.45
      Expr_String_Literal,  -- e.g., "Hello"
      Expr_Variable,        -- e.g., SALARY
      Expr_Binary_Op,       -- e.g., A + B
      Expr_Unary_Op,        -- e.g., -A
      Expr_Function_Call    -- e.g., SQRT(X)
   );

   --  Arithmetic and logical binary operators.
   type Binary_Op is (Op_Add, Op_Sub, Op_Mul, Op_Div, Op_Pow, Op_Eq, Op_Ne, Op_Lt, Op_Le, Op_Gt, Op_Ge);
   
   --  Unary operators.
   type Unary_Op is (Op_Neg);

   type Expression;
   type Expression_Access is access Expression;

   --  Linked list structure for function arguments.
   type Expression_List_Node;
   type Expression_List is access Expression_List_Node;
   type Expression_List_Node is record
      Expr : Expression_Access;
      Next : Expression_List;
   end record;

   --  Variant record for all expression types.
   type Expression (Kind : Expression_Kind) is record
      case Kind is
         when Expr_Numeric_Literal =>
            Value : Float;
         when Expr_String_Literal =>
            Str_Value : String (1 .. 1024);
            Str_Length : Natural;
         when Expr_Variable =>
            Var_Name : String (1 .. 32);
            Var_Len  : Natural;
         when Expr_Binary_Op =>
            Left  : Expression_Access;
            Right : Expression_Access;
            Op    : Binary_Op;
         when Expr_Unary_Op =>
            Operand : Expression_Access;
            UOp     : Unary_Op;
         when Expr_Function_Call =>
            Func_Name : String (1 .. 32);
            Func_Len  : Natural;
            Arguments : Expression_List;
      end case;
   end record;

   --  Represents a single variable or a range (e.g., VAR1-VAR10).
   type Variable_Range is record
      Start_Name : String (1 .. 32);
      Start_Len  : Natural;
      End_Name   : String (1 .. 32);
      End_Len    : Natural;
      Is_Range   : Boolean := False;
   end record;

   --  Linked list for variable lists in KEEP/DROP statements.
   type Variable_List_Node;
   type Variable_List is access Variable_List_Node;
   type Variable_List_Node is record
      Var  : Variable_Range;
      Next : Variable_List;
   end record;

   --  Types of statements (commands) available in SData.
   type Statement_Kind is (
      Stmt_LET,    -- Variable assignment
      Stmt_PRINT,  -- Output to console
      Stmt_USE,    -- Load dataset
      Stmt_SAVE,   -- Save dataset
      Stmt_KEEP,   -- Keep specific columns
      Stmt_DROP,   -- Drop specific columns
      Stmt_IF,     -- Conditional execution (placeholder)
      Stmt_FOR,    -- Loop (placeholder)
      Stmt_WHILE,  -- Loop (placeholder)
      Stmt_REPEAT, -- Loop (placeholder)
      Stmt_END,    -- Terminate program
      Stmt_QUIT,   -- Terminate program
      Stmt_NAMES   -- List column names
   );

   type Statement;
   type Statement_Access is access Statement;

   --  Variant record for statements. Linked via the 'Next' pointer to form a program.
   type Statement (Kind : Statement_Kind) is record
      Next : Statement_Access; -- Pointer to the next statement in sequence.
      case Kind is
         when Stmt_LET =>
            Var_Name : String (1 .. 32);
            Var_Len  : Natural;
            Expr     : Expression_Access;
         when Stmt_PRINT =>
            Print_Expr : Expression_Access; -- null means "PRINT all columns"
         when Stmt_USE | Stmt_SAVE =>
            File_Path : String (1 .. 1024);
            File_Len  : Natural;
         when Stmt_KEEP | Stmt_DROP =>
            Vars : Variable_List;
         when others =>
            null;
      end case;
   end record;

end SData.AST;
