-- Test AND, OR, XOR logical operators
NEW
REPEAT 1
IF 1 AND 1 THEN PRINT "1 AND 1 IS TRUE"
IF 1 AND 0 THEN PRINT "1 AND 0 IS TRUE"
IF 0 AND 1 THEN PRINT "0 AND 1 IS TRUE"
IF 0 AND 0 THEN PRINT "0 AND 0 IS TRUE"

IF 1 OR 1 THEN PRINT "1 OR 1 IS TRUE"
IF 1 OR 0 THEN PRINT "1 OR 0 IS TRUE"
IF 0 OR 1 THEN PRINT "0 OR 1 IS TRUE"
IF 0 OR 0 THEN PRINT "0 OR 0 IS TRUE"

IF 1 XOR 1 THEN PRINT "1 XOR 1 IS TRUE"
IF 1 XOR 0 THEN PRINT "1 XOR 0 IS TRUE"
IF 0 XOR 1 THEN PRINT "0 XOR 1 IS TRUE"
IF 0 XOR 0 THEN PRINT "0 XOR 0 IS TRUE"
RUN
QUIT
