-- Test SELECT with LAG, NEXT, RECNO
REPEAT 10
LET X = RECNO
RUN

SELECT X > 2 AND X < 9 AND MOD(X, 2) = 0
RUN
PRINT "X:" X "LAG:" LAG("X") "NEXT:" NEXT("X") "OBS:" OBS("X", 2) "RECNO:" RECNO "ORD:" ORD "ORD(X):" ORD(STR$(X)) "BOF:" BOF "EOF:" EOF
RUN
QUIT
