-- SUBMIT nesting-depth limit: a chain of distinct files deeper than the limit
-- must fail with a clear error rather than overflowing the stack.  The chain
-- (tests/data/submit_depth_gen/c001..c065) is generated by `make check`.
SUBMIT "tests/data/submit_depth_gen/c001.cmd"
RUN
QUIT
