USE "mock"

PRINT "ID BEFORE:"
PRINT ID
LET ID = "StringVal"
PRINT "ID AFTER (Should match BEFORE):"
PRINT ID

PRINT "NAME BEFORE:"
PRINT NAME
LET NAME = 999.0
PRINT "NAME AFTER (Should match BEFORE):"
PRINT NAME
